Consider the below code to answer further questions:



In [20]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [21]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Queston 1 : Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables

Answer:-Yes, there is a difference in the data types of the variables list_ and array_list.
list_ is a Python list.
array_list is a NumPy array.
Although they both contain the same string values, they have different data types because they are different types of objects.

Code to check type below :

In [22]:
import numpy as np

# Example list and NumPy array
list_ = [1, 2, 3, 4, 5]
array_list = np.array(list_)

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Answer:-

In [23]:
import numpy as np

# Example list and NumPy array
list_ = [1, 2, 3, 4, 5]
array_list = np.array(list_)

# Print the data type of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Answer:-Yes, there will be a difference in the data types of the elements present in list_ and array_list.

list_ is a Python list, and the elements will have their original data types, which are typically int.

array_list is a NumPy array, and when you specify dtype=int, the elements are converted to int64 (or int32 depending on the platform).

Code to Print Data Types of Each Element
Here is the code to check and print the data types of each and every element in both variables, list_ and array_list:

In [27]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [26]:
import numpy as np

# Original list
list_ = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print the data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print the data types of each element in array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

In [28]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [29]:
num_array


array([[1, 2, 3],
       [4, 5, 6]])

Question 4: Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

Answer:-

In [30]:
# Showing num_array shape
num_array.shape

(2, 3)

In [31]:
# Showing num_array shape
num_array.shape

(2, 3)

Question 5: Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

Answer:-

In [32]:
import numpy as np

# Create a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

# Print the matrix
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# Verifying Matrix size and shape
print(f'Size of arr5 is {zero_matrix.size}')
print(f'Shape of arr5 is {zero_matrix.shape}')

Size of arr5 is 9
Shape of arr5 is (3, 3)


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Answer:-

In [35]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
